apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: protonmail-bridge
      app.kubernetes.io/part-of: philanthropy-os

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: shenxn/protonmail-bridge
    newTag: 3.19.0-build
