apiVersion: v1
kind: Service
metadata:
  name: protonmail-bridge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: protonmail-bridge
  ports:
    - name: smtp
      port: 25
      targetPort: smtp
    - name: imap
      port: 143
      targetPort: imap
